language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.2
  - 2.2.0
  - 2.3.0
before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo sqlite3 -version
  - sudo psql --version
  - sudo mysql --version
  - gem update bundler
