language: ruby
notifications:
  email: false
rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
env:
  matrix:
    - DB=pg
    - DB=mysql
    - DB=sqlite
before_install:
  - sh -c "if [ '$DB' = 'sqlite' ]; then ./ci/install_modern_sqlite.sh; fi;"
before_script:
  - rake db:setup
